### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#14]
Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.5/site-packages/telethon/update_state.py", line 119, in _worker_loop
    handler(update)
  File "./telegramircd.py", line 2011, in on_telegram_update
    getattr(TelegramUpdate, name)(self, update)
  File "./telegramircd.py", line 1666, in UpdateNewChannelMessage
    server.on_telegram_update_message(update, update.message)
  File "./telegramircd.py", line 2056, in on_telegram_update_message
    text = '[{}] {}'.format(type(msg.media).__name__, msg.media.to_dict())
TypeError: 'str' object is not callable

**Comment by MaskRay** [comment]
Yes in an old commit `.name` was used, which should be `.__name__`.

**Comment by MaskRay** [comment]
Sorry it had another issue.... I should not have used `type` ... It is now fixed
