### ISSUE TITLE
Login failed if the account's 2FA is enabled

### ISSUE THREAD

**Issue by ghost** [MaskRay/telegramircd#20]
Hello.
I found a problem that the program init will be failed if the account's 2FA is enabled.
When entering the login code, the program will be restarted without any notification for entering 2FA password. The error log is there:
```DEBUG: Confirmed SignInRequest through error Two-steps verification is enabled and a password is required
Traceback (most recent call last):
  File "telegramircd.py", line 658, in oper
    ok = web.proc.sign_in(options.tg_phone, password)
  File "/lib/python3.5/site-packages/telethon/telegram_client.py", line 435, in sign_in
    result = self(SignInRequest(phone, phone_code_hash, str(code)))
  File "/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 461, in __call__
    result = self._invoke(call_receive, *requests)
  File "/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 558, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.SessionPasswordNeededError: Two-steps verification is enabled and a password is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "telegramircd.py", line 1560, in handle_irc
    self.handle_command(command, args)
  File "telegramircd.py", line 1516, in handle_command
    fn(*ba.args)
  File "telegramircd.py", line 661, in oper
    except SessionPasswordNeededError:
NameError: name 'SessionPasswordNeededError' is not defined
```

**Comment by aconitumnapellus** [comment]
@HILIS To workaround / fix this problem, add this line in the header of the file:
from telethon.errors import SessionPasswordNeededError
Look at my pull request to see what i mean #22

**Comment by MaskRay** [comment]
#22 has been merged for some time....
