### ISSUE TITLE
Error when downloading media

### ISSUE THREAD

**Issue by jreinert** [MaskRay/telegramircd#21]
See https://github.com/LonamiWebs/Telethon/issues/855

**Comment by prsai** [comment]
I have the exactly same error, in IRC when there is a link to a file
example:

`<user> [photo] http://127.1:9003/document/0.jpg`

And I try to access it from a web browser it's not working and I get in telegramircd:

```
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/home/tg/.local/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/home/tg/.local/lib/python3.5/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/home/tg/.local/lib/python3.5/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/home/tg/.local/lib/python3.5/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/home/tg/.local/lib/python3.5/site-packages/aiohttp/http_writer.py", line 111, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 138, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 110, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None

```
The problem seems not to be in telethon but in aiohttp or in telegramircd I don't know.

Please Maskray could you have a look? Thanks.

**Comment by MaskRay** [comment]
Are you using telethon-sync? telegramircd is not compatible with the asynchronous version of telethon.

**Comment by prsai** [comment]
I use telethon-sync

But I have applied the change https://github.com/alecdwm/telegramircd/commit/6aebc5c6c29e85a091e703929aed3d15030a87ce from alecdwm forked repository and by now it's working! (I have to do some more tests though)

I have cherry picked this change into my forked repository: https://github.com/prsai/telegramircd, if you pull don't forget to install python-magic:
`pip3 install python-magic`

**Comment by MaskRay** [comment]
Thank you for the pointer! Cherry-picked alecdwm@6aebc5c
