### ISSUE TITLE
Not connecting to Telegram

### ISSUE THREAD

**Issue by EDmitry** [MaskRay/telegramircd#23]
I am running the server like this:
~/telegramircd$ ./telegramircd.py  -c config
./telegramircd.py:111: RuntimeWarning: coroutine 'TelegramBaseClient.connect' was never awaited
  self.proc.connect()
Traceback (most recent call last):
  File "./telegramircd.py", line 294, in init
    web.get_self()
  File "./telegramircd.py", line 290, in get_self
    server.user_id = data.id
AttributeError: 'coroutine' object has no attribute 'id'
./telegramircd.py:298: RuntimeWarning: coroutine 'UserMethods.get_me' was never awaited
  traceback.print_exc()
INFO: ubuntu!weechat@127.0.0.1 registered

I am able to connect to it via WeeChat and join #telegram, but nothing happens past that. I don't receive the code for oper. Is there any additional logging I could collect to figure out what's wrong?

**Comment by EDmitry** [comment]
I think this might be related to this issue: https://github.com/LonamiWebs/Telethon/issues/1180

I wasn't able to install telethon-sync, and instead used telethon.

**Comment by EDmitry** [comment]
Downgraded telethon and now getting this error when retrieving the channel list:

INFO: Connecting to 149.154.175.100:443...
INFO: Connection success!
INFO: Initializing a new connection while invoking
INFO: Starting to wait for items from the network
/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py:2541: UserWarning: You have not setup any workers, so you won't receive updates. Pass update_workers=1 when creating the TelegramClient, or set client.self.updates.workers = 1
  "You have not setup any workers, so you won't receive updates."
Traceback (most recent call last):
  File "./telegramircd.py", line 295, in init
    web.channel_list()
  File "./telegramircd.py", line 265, in channel_list
    hash=0
TypeError: __init__() got an unexpected keyword argument 'hash'
INFO: ubuntu!weechat@127.0.0.1 registered

**Comment by rodneyrod** [comment]
Having the same issue when trying to create a new deployment, might need to be refactored to use the latest version of Telethon, or the old version of telegram-sync might need to be hosted somewhere else.

**Comment by rodneyrod** [comment]
If it helps I located some legacy versions hosted elsewhere:
https://nero-mirror.stanford.edu/pypi/web/simple/telethon-sync/

**Comment by rodneyrod** [comment]
Tried with the last version of Telethon-Sync I could find, v1.1.1, however it never loads events and the following is listed in the terminal:

```
telegramircd.py:135: DeprecationWarning: Application.make_handler(...) is deprecated, use AppRunner API instead
  self.handler = self.app.make_handler()
telegramircd.py:111: RuntimeWarning: coroutine 'TelegramBaseClient.connect' was never awaited
  self.proc.connect()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "telegramircd.py", line 294, in init
    web.get_self()
  File "telegramircd.py", line 290, in get_self
    server.user_id = data.id
AttributeError: 'coroutine' object has no attribute 'id'
telegramircd.py:298: RuntimeWarning: coroutine 'UserMethods.get_me' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by rodneyrod** [comment]
No luck finding an old version of telethon-sync hosted anywhere either, and I have a feeling the Telethon dev probably won't be supplying those by request as they were forcably deprecated.

**Comment by MaskRay** [comment]
I never learned how to use Python async/await properly... It seems that migrating to Telethon requires quite amount of work and many methods may need to be turned `async`. Is that right?
