### ISSUE TITLE
Something Error...

### ISSUE THREAD

**Issue by kingcc** [MaskRay/telegramircd#3]
你好。
当我运行./telegramircd.py时，报错：

INFO: 127.0.0.1 - - [06/Dec/2016:09:21:22 +0000] "GET /app.js HTTP/1.1" 200 3143478 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"
INFO: WebSocket client connected from ('127.0.0.1', 60470)
ERROR: Error handling request
Traceback (most recent call last):
  File "/home/kin/.local/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/home/kin/.local/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
    resp = yield from handler(request)
  File "./telegramircd.py", line 66, in handle_web_socket
    Server.instance.on_websocket(data)
  File "./telegramircd.py", line 1602, in on_websocket
    client.on_websocket(data)
  File "./telegramircd.py", line 1377, in on_websocket
    getattr(SpecialCommands, command)(self, data)
  File "./telegramircd.py", line 478, in room
    room = client.ensure_special_room(record)
  File "./telegramircd.py", line 1134, in ensure_special_room
    assert isinstance(record['flags'], int)
KeyError: 'flags'

**Comment by MaskRay** [comment]
棄用 webogram 改用 telegram-cli 了……還有這個問題嗎？
