### ISSUE TITLE
telegramircd crashed intermittently

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#5]
Below is the dump from the program:

INFO: [IRC NAME]![HOSTNAME]@127.0.0.1 registered
ERROR: Task exception was never retrieved
future: <Task finished coro=<Web.handle_telegram_cli() done, defined at /home/[USERNAME]/git/telegramircd/telegramircd.py:106> exception=AttributeError("'Web' object has no attribute 'message'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/[USERNAME]/git/telegramircd/telegramircd.py", line 132, in handle_telegram_cli
    Server.instance.on_telegram_cli(data)
  File "/home/[USERNAME]/git/telegramircd/telegramircd.py", line 1717, in on_telegram_cli
    client.on_telegram_cli(data)
  File "/home/[USERNAME]/git/telegramircd/telegramircd.py", line 1515, in on_telegram_cli
    getattr(SpecialCommands, name)(self, data)
  File "/home/[USERNAME]/git/telegramircd/telegramircd.py", line 595, in message
    client.ensure_special_room(data['to']).on_telegram_cli_message(data)
  File "/home/[USERNAME]/git/telegramircd/telegramircd.py", line 1143, in on_telegram_cli_message
    irc_message(self.client, sender, self.name, self, data)
  File "/home/[USERNAME]/git/telegramircd/telegramircd.py", line 291, in irc_message
    del web.message[msg['id']]
AttributeError: 'Web' object has no attribute 'message'

**Comment by MaskRay** [comment]
It has been fixed in `HEAD`. `git pull`

**Comment by rodneyrod** [comment]
Thanks, I'll keep the process active and see if it happens again. If I get no problems in a week I'll close this issue.

**Comment by rodneyrod** [comment]
I've gotten these errors a couple of times, but so far everything looks to be staying connected so it's probably just a very minor bug:

ERROR: Task exception was never retrieved
future: <Task finished coro=<Web.channel_members() done, defined at telegramircd.py:250> exception=TelegramCliFail('fail',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "telegramircd.py", line 252, in channel_members
    await self.chat_info(channel)
  File "telegramircd.py", line 222, in chat_info
    data = await self.send_command('chat_info {}'.format(channel.peer))
  File "telegramircd.py", line 67, in send_command
    raise TelegramCliFail('fail')
TelegramCliFail: fail
ERROR: Task exception was never retrieved
future: <Task finished coro=<Web.handle_telegram_cli() done, defined at telegramircd.py:110> exception=AttributeError("'SpecialUser' object has no attribute 'ensure_special_user'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "telegramircd.py", line 136, in handle_telegram_cli
    Server.instance.on_telegram_cli(data)
  File "telegramircd.py", line 1763, in on_telegram_cli
    client.on_telegram_cli(data)
  File "telegramircd.py", line 1545, in on_telegram_cli
    getattr(SpecialCommands, name)(self, data)
  File "telegramircd.py", line 625, in message
    client.ensure_special_user(data['to']).on_telegram_cli_message(data)
  File "telegramircd.py", line 1667, in on_telegram_cli_message
    sender = self.ensure_special_user(data['from'])
AttributeError: 'SpecialUser' object has no attribute 'ensure_special_user'

**Comment by MaskRay** [comment]
> File "telegramircd.py", line 67, in send_command
> raise TelegramCliFail('fail')
> TelegramCliFail: fail
It was strange that it the response to `chat_info` were not complete after 10 `reader.read(4096)`.


> File "telegramircd.py", line 1667, in on_telegram_cli_message
> sender = self.ensure_special_user(data['from'])
Sorry, I have fixed this bug recently... It should be `self.client.ensure_special_user`

**Comment by rodneyrod** [comment]
Issue hasn't occurred again as far as I can see, closing this issue.
